/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.main;

import com.java.swingExample.*;
import com.java.main.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhi
 */
public class BillChallanFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalBillChallan
     */
    
    Statement st;
    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    int order_no=0;
    public BillChallanFrame() {
        con =  DBConnection.getCon();
        initComponents();
        setSize(700, 650); 
	setLocation(300, 20);
        setClosable(true); 
        setIconifiable(true);
        try {
              st=con.createStatement();
              rs=st.executeQuery("select max(bill_no) from bill_challan_master");
           
              rs.next();
              if(rs!=null)
              {
                  order_no=rs.getInt(1);
                  order_no++;
              } 
           else
                    order_no=1;
              
              orderNoTextField.setText("IHFL/00"+order_no);
                       
        } catch (Exception ex) {
            Logger.getLogger(BillChallanFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        orderNoTextField.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billChallanScrollPane = new javax.swing.JScrollPane();
        billChallanPanel = new javax.swing.JPanel();
        companyDetailsLabel = new javax.swing.JPanel();
        landlineLabelValue = new javax.swing.JLabel();
        websiteLabelValue = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        landlineLabel = new javax.swing.JLabel();
        websiteLabel = new javax.swing.JLabel();
        emailIdLabel = new javax.swing.JLabel();
        mobileLabelValue = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        orderNoTextField = new javax.swing.JTextField();
        receiverDetailsLabel = new javax.swing.JLabel();
        mrLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTextField = new javax.swing.JTextField();
        productsLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        senderDetailsLabel = new javax.swing.JLabel();
        senderDetailsTextField = new javax.swing.JTextField();
        spreadingLabel = new javax.swing.JLabel();
        dateLabelCopy = new javax.swing.JLabel();
        orderLabelCopy = new javax.swing.JLabel();
        orderNoTextFieldCopy = new javax.swing.JTextField();
        nameTextFieldCopy = new javax.swing.JTextField();
        nameLabelCopy = new javax.swing.JLabel();
        addressLabelCopy = new javax.swing.JLabel();
        thankYouNoteLabel = new javax.swing.JLabel();
        messageLabel1 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        productNameLabel = new javax.swing.JLabel();
        productList = new javax.swing.JComboBox<>();
        addProductBtn = new javax.swing.JButton();
        pLabel1 = new javax.swing.JLabel();
        p2Label = new javax.swing.JLabel();
        p3Label = new javax.swing.JLabel();
        p4Label = new javax.swing.JLabel();
        p5Label = new javax.swing.JLabel();
        p6Label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();
        addressLine1TextField = new javax.swing.JTextField();
        addressLine1TextFieldCopy = new javax.swing.JTextField();
        dateChooserCopy = new com.toedter.calendar.JDateChooser();
        addressLabel2 = new javax.swing.JLabel();
        addressLine2TextField = new javax.swing.JTextField();
        addressLine2LabelCopy = new javax.swing.JLabel();
        addressLine2TextFieldCopy = new javax.swing.JTextField();
        thanksMessage = new javax.swing.JTextField();
        thanksMessage1 = new javax.swing.JTextField();

        landlineLabelValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        landlineLabelValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        landlineLabelValue.setText("011-2458967");
        landlineLabelValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        websiteLabelValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        websiteLabelValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        websiteLabelValue.setText("www.happyflowers.com");
        websiteLabelValue.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("happyflowers@gmail.com");
        emailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        mobileLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobileLabel.setText("Mera Mobile");

        landlineLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        landlineLabel.setText("Landline");

        websiteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        websiteLabel.setText("Website");

        emailIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailIdLabel.setText("Email Id");

        mobileLabelValue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobileLabelValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobileLabelValue.setText("9999633345");
        mobileLabelValue.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout companyDetailsLabelLayout = new javax.swing.GroupLayout(companyDetailsLabel);
        companyDetailsLabel.setLayout(companyDetailsLabelLayout);
        companyDetailsLabelLayout.setHorizontalGroup(
            companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, companyDetailsLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(emailIdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(landlineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlineLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(websiteLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(websiteLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(mobileLabel)
                        .addGap(18, 18, 18)
                        .addComponent(mobileLabelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35))
        );
        companyDetailsLabelLayout.setVerticalGroup(
            companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileLabel)
                    .addComponent(mobileLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(landlineLabel)
                    .addComponent(landlineLabelValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(websiteLabelValue)
                    .addComponent(websiteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailIdLabel)))
        );

        logoPanel.setToolTipText("Uploaded Logo Image");
        logoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        headerLabel.setFont(new java.awt.Font("Lucida Handwriting", 1, 16)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 51, 51));
        headerLabel.setText("24X7 Flowers,Cakes & Gifts Services in India & Around the World.");
        headerLabel.setAlignmentX(20.0F);

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLabel.setText("Date");

        orderLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderLabel.setText("Order No");

        orderNoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNoTextFieldActionPerformed(evt);
            }
        });

        receiverDetailsLabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        receiverDetailsLabel.setText("Receiver Details");

        mrLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mrLabel.setText("Mr. /Mrs. Miss");

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressLabel.setText("Address Line1");

        telephoneLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        telephoneLabel.setText("Telephone");

        telephoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneTextFieldActionPerformed(evt);
            }
        });

        productsLabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        productsLabel.setText("Products Details");

        messageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messageLabel.setText("Message");

        senderDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        senderDetailsLabel.setText("Sender Details");

        senderDetailsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderDetailsTextFieldActionPerformed(evt);
            }
        });

        spreadingLabel.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        spreadingLabel.setForeground(new java.awt.Color(255, 51, 51));
        spreadingLabel.setText("Spreading Happiness on Plant Earth with flowers");

        dateLabelCopy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLabelCopy.setText("Date");

        orderLabelCopy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderLabelCopy.setText("Order No");

        nameLabelCopy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nameLabelCopy.setText("Mr. /Mrs. Miss");

        addressLabelCopy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressLabelCopy.setText("Address Line1");

        thankYouNoteLabel.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        thankYouNoteLabel.setForeground(new java.awt.Color(255, 51, 51));
        thankYouNoteLabel.setText("Thanking You Note");

        messageLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messageLabel1.setText("Message");

        productNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productNameLabel.setText("Product Name");

        productList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cake", "Chocolate", "Flower", "Gift Items" }));

        addProductBtn.setBackground(new java.awt.Color(51, 51, 255));
        addProductBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addProductBtn.setText("Add");
        addProductBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductBtnActionPerformed(evt);
            }
        });

        pLabel1.setText("P1");

        p2Label.setText("P2");

        p3Label.setText("p3");

        p4Label.setText("p4");

        p5Label.setText("p5");

        p6Label.setText("p6");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printBtn.setText("PRINT");
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
        });
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(printBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        addressLine1TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine1TextFieldActionPerformed(evt);
            }
        });

        addressLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressLabel2.setText("Address Line2");

        addressLine2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressLine2TextFieldActionPerformed(evt);
            }
        });

        addressLine2LabelCopy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressLine2LabelCopy.setText("Address Line2");

        javax.swing.GroupLayout billChallanPanelLayout = new javax.swing.GroupLayout(billChallanPanel);
        billChallanPanel.setLayout(billChallanPanelLayout);
        billChallanPanelLayout.setHorizontalGroup(
            billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billChallanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(senderDetailsLabel)
                                    .addComponent(messageLabel))
                                .addGap(18, 18, 18)
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(senderDetailsTextField)
                                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addGap(243, 243, 243)
                                .addComponent(thankYouNoteLabel))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addressLine1TextField))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addComponent(productNameLabel)
                                .addGap(18, 18, 18)
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                                        .addComponent(productList, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(addProductBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(pLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(p2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(p5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p6Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(spreadingLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createSequentialGroup()
                                .addComponent(productsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addComponent(addressLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addressLine2TextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createSequentialGroup()
                                .addComponent(dateLabelCopy)
                                .addGap(67, 67, 67)
                                .addComponent(dateChooserCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(orderLabelCopy)
                                .addGap(18, 18, 18)
                                .addComponent(orderNoTextFieldCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameLabelCopy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addressLabelCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTextFieldCopy)
                                    .addComponent(addressLine1TextFieldCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addComponent(addressLine2LabelCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(thanksMessage)
                                    .addComponent(addressLine2TextFieldCopy, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                                    .addComponent(thanksMessage1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(messageLabel1)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephoneLabel)
                                    .addComponent(orderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createSequentialGroup()
                                        .addComponent(orderNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dateLabel)
                                        .addGap(44, 44, 44)
                                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(companyDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(receiverDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        billChallanPanelLayout.setVerticalGroup(
            billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billChallanPanelLayout.createSequentialGroup()
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(companyDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerLabel)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(orderLabel)
                            .addComponent(orderNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateLabel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(receiverDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLine1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLine2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel)
                    .addComponent(productList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pLabel1)
                    .addComponent(p2Label)
                    .addComponent(p3Label))
                .addGap(18, 18, 18)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4Label)
                    .addComponent(p5Label)
                    .addComponent(p6Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senderDetailsLabel)
                    .addComponent(senderDetailsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spreadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateLabelCopy)
                        .addComponent(orderLabelCopy)
                        .addComponent(orderNoTextFieldCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateChooserCopy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextFieldCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabelCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabelCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLine1TextFieldCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLine2LabelCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLine2TextFieldCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(thankYouNoteLabel)
                .addGap(12, 12, 12)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel1)
                    .addComponent(thanksMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thanksMessage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        billChallanScrollPane.setViewportView(billChallanPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billChallanScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(billChallanScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telephoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneTextFieldActionPerformed

    private void senderDetailsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderDetailsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senderDetailsTextFieldActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try
    { 
            System.out.println("Connection created successfully : "+con.getSchema());
     pst=con.prepareStatement("insert into bill_challan_master(order_no,challan_date,name,address_line1,address_line2,telephone,sender_message,sender_details,thank_you_message) values(?,?,?,?,?,?,?,?,?)");
     System.out.println("Connection Size : "+pst.getFetchSize());
     pst.setString(1,""+orderNoTextField.getText());
     pst.setString(2,""+"09-09-2017");
     pst.setString(3,""+nameTextField.getText());
     pst.setString(4,""+addressLine1TextField.getText());
     pst.setString(5,""+addressLine2TextField.getText());
     pst.setString(6,""+telephoneTextField.getText());
     pst.setString(7,""+messageTextField.getText());
     pst.setString(8,""+senderDetailsTextField.getText());
     pst.setString(9,""+thanksMessage.getText());
    

     System.out.println("Setting values to db : ");
     saveBtn.setEnabled(true);
     pst.executeUpdate();
     System.out.println("Executed successfully");
     JOptionPane.showMessageDialog(null, "Record Inserted Sucessfully...."); 
     new BillChallanFrame();
     orderNoTextField.setText("");
     nameTextField.setText("");
     addressLine1TextField.setText("");
     addressLine2TextField.setText("");
     telephoneTextField.setText("");
     messageTextField.setText("");
     senderDetailsTextField.setText("");
     thanksMessage.setText("");
     con.close();

        }                                    
        catch(Exception ex)
        {
            System.out.println("Exception : "+ex);
        }
    }                                       

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked

    }//GEN-LAST:event_printBtnMouseClicked

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed

        String inFileName="invoice"+System.currentTimeMillis()+".png";
		String outFileName="invoice"+System.currentTimeMillis()+".pdf";
		
		 BufferedImage img = Printer.getScreenShot(
	                this.getContentPane() );
		 JOptionPane.showMessageDialog(
	                null,
	                new JLabel(
	                  "Invoice Printed"));
	              try {
	                // write the image as a PNG
	                ImageIO.write(
	                  img,
	                  "png",
	                  new File(inFileName));
	              } catch(Exception e) {
	                e.printStackTrace();
	              }
		 
		 try {
			Image2Pdf.convertJPGToPDF(outFileName,ImageIO.read(new File(inFileName)));
		} catch (Exception e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		}
      
    }//GEN-LAST:event_printBtnActionPerformed

    private void orderNoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderNoTextFieldActionPerformed

    private void addressLine1TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine1TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine1TextFieldActionPerformed

    private void addressLine2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressLine2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressLine2TextFieldActionPerformed

    private void addProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductBtnActionPerformed
        // TODO add your handling code here:
        
        List list = new ArrayList();
        
        
       
    }//GEN-LAST:event_addProductBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductBtn;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel2;
    private javax.swing.JLabel addressLabelCopy;
    private javax.swing.JTextField addressLine1TextField;
    private javax.swing.JTextField addressLine1TextFieldCopy;
    private javax.swing.JLabel addressLine2LabelCopy;
    private javax.swing.JTextField addressLine2TextField;
    private javax.swing.JTextField addressLine2TextFieldCopy;
    private javax.swing.JPanel billChallanPanel;
    private javax.swing.JScrollPane billChallanScrollPane;
    private javax.swing.JPanel companyDetailsLabel;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dateChooserCopy;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabelCopy;
    private javax.swing.JLabel emailIdLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel landlineLabel;
    private javax.swing.JLabel landlineLabelValue;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JLabel mobileLabelValue;
    private javax.swing.JLabel mrLabel;
    private javax.swing.JLabel nameLabelCopy;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField nameTextFieldCopy;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel orderLabelCopy;
    private javax.swing.JTextField orderNoTextField;
    private javax.swing.JTextField orderNoTextFieldCopy;
    private javax.swing.JLabel p2Label;
    private javax.swing.JLabel p3Label;
    private javax.swing.JLabel p4Label;
    private javax.swing.JLabel p5Label;
    private javax.swing.JLabel p6Label;
    private javax.swing.JLabel pLabel1;
    private javax.swing.JButton printBtn;
    private javax.swing.JComboBox<String> productList;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel productsLabel;
    private javax.swing.JLabel receiverDetailsLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel senderDetailsLabel;
    private javax.swing.JTextField senderDetailsTextField;
    private javax.swing.JLabel spreadingLabel;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JLabel thankYouNoteLabel;
    private javax.swing.JTextField thanksMessage;
    private javax.swing.JTextField thanksMessage1;
    private javax.swing.JLabel websiteLabel;
    private javax.swing.JLabel websiteLabelValue;
    // End of variables declaration//GEN-END:variables
}
