/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.main;

import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhi
 */
public class InvoiceTaxForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form TaxInvoiceInternal
     */
    public InvoiceTaxForm() {
        initComponents();
        setResizable(false);
        setClosable(true);
        setSize(1250, 700); 
	setLocation(50, 10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taxDetailsPanel1 = new javax.swing.JPanel();
        headerTitlePanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        emailLable = new javax.swing.JLabel();
        mobileLable = new javax.swing.JLabel();
        taxDetailsPanel2 = new javax.swing.JPanel();
        gstInLabel = new javax.swing.JLabel();
        gstInValue = new javax.swing.JLabel();
        taxChargeLabel = new javax.swing.JLabel();
        taxComboOption = new javax.swing.JComboBox<>();
        invoiceSeriaValue = new javax.swing.JLabel();
        vehicleNoLabel = new javax.swing.JLabel();
        transportModeLabel = new javax.swing.JLabel();
        placeSupplyLabel = new javax.swing.JLabel();
        vehicleNoValue = new javax.swing.JTextField();
        transportModeValue = new javax.swing.JTextField();
        supplyPlaceValue = new javax.swing.JTextField();
        invoiceSerialLabel = new javax.swing.JLabel();
        deliveryDetailsPanel = new javax.swing.JPanel();
        recieverDetailsLabel = new javax.swing.JLabel();
        receiverNameLabel = new javax.swing.JLabel();
        consigneelabel = new javax.swing.JLabel();
        consigneeDetailsLabel = new javax.swing.JLabel();
        consigneeAddressLabel = new javax.swing.JLabel();
        consigneeNamevalue = new javax.swing.JTextField();
        consigneeAddressValue = new javax.swing.JTextField();
        receiverAddressLabel = new javax.swing.JLabel();
        receiverStatelabel = new javax.swing.JLabel();
        receiverNameValue = new javax.swing.JTextField();
        receiverAddressvalue = new javax.swing.JTextField();
        consigneeStateLabel = new javax.swing.JLabel();
        consigneeStatevalue = new javax.swing.JTextField();
        receiverStateValue = new javax.swing.JTextField();
        receiverMobileLabel = new javax.swing.JLabel();
        receiverMobileValue = new javax.swing.JTextField();
        consigneeMobileValue = new javax.swing.JTextField();
        consigneeMobilelabel = new javax.swing.JLabel();
        receiverEmailValue = new javax.swing.JTextField();
        receiverEmailLabel = new javax.swing.JLabel();
        consigneeEmailValue = new javax.swing.JTextField();
        consigneeEmailLabel = new javax.swing.JLabel();
        receiverGSTLabel = new javax.swing.JLabel();
        consigneeGSTLabel = new javax.swing.JLabel();
        receiverGSTValue = new javax.swing.JTextField();
        consigneeGSTValue = new javax.swing.JTextField();
        AddProductPanel = new javax.swing.JPanel();
        productNameLabel = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        productHSNCodeLabel = new javax.swing.JLabel();
        productHsnCodeValue = new javax.swing.JTextField();
        productRateLabel = new javax.swing.JLabel();
        productyQuantityValue = new javax.swing.JTextField();
        productRateValue = new javax.swing.JTextField();
        productQuantityLabel = new javax.swing.JLabel();
        addProductButton = new javax.swing.JButton();
        productTableScroll = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        footerPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        taxCalculationPanel = new javax.swing.JPanel();
        freightLabel = new javax.swing.JLabel();
        freighValueLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        totalValueLabel = new javax.swing.JLabel();
        CGSTValueLabel = new javax.swing.JLabel();
        CGSTLabel = new javax.swing.JLabel();
        SGSTValueLabel = new javax.swing.JLabel();
        SGSTLabel = new javax.swing.JLabel();
        IGSTValueLabel = new javax.swing.JLabel();
        IGSTLabel = new javax.swing.JLabel();
        grandTotalValueLabel = new javax.swing.JLabel();
        grandTotalLabel = new javax.swing.JLabel();
        cgstTextField = new javax.swing.JTextField();
        SGSTTextField = new javax.swing.JTextField();
        IGSTTextField = new javax.swing.JTextField();

        taxDetailsPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        headerLabel.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 51, 51));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Happy Flowers");
        headerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("A-24 , Ganesh Nagar, Pandav Nagar Complex,Delhi-92");
        addressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        emailLable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        emailLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLable.setText("Email : florishtth@gmail.com");
        emailLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mobileLable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mobileLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobileLable.setText("Mob : 9999633345,8800675678");
        mobileLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout headerTitlePanelLayout = new javax.swing.GroupLayout(headerTitlePanel);
        headerTitlePanel.setLayout(headerTitlePanelLayout);
        headerTitlePanelLayout.setHorizontalGroup(
            headerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerTitlePanelLayout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(280, 280, 280))
            .addGroup(headerTitlePanelLayout.createSequentialGroup()
                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(emailLable, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mobileLable, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerTitlePanelLayout.setVerticalGroup(
            headerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerTitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(headerTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(emailLable)
                    .addComponent(mobileLable)))
        );

        taxDetailsPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gstInLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel.setText("GSTIN Number   :");

        gstInValue.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInValue.setText("HJVGHFGFAHJHJD");

        taxChargeLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        taxChargeLabel.setText("Tax is on Reverse Charge  :");

        taxComboOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        taxComboOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxComboOptionActionPerformed(evt);
            }
        });

        invoiceSeriaValue.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSeriaValue.setText("FLGJJGD54554");

        vehicleNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        vehicleNoLabel.setText("Vehicle No :");

        transportModeLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        transportModeLabel.setText("Transport Mode   :");

        placeSupplyLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel.setText("Place of Supply : ");

        vehicleNoValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoValueActionPerformed(evt);
            }
        });

        transportModeValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        transportModeValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportModeValueActionPerformed(evt);
            }
        });

        supplyPlaceValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        invoiceSerialLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSerialLabel.setText("Invoice Serial No : ");

        javax.swing.GroupLayout taxDetailsPanel2Layout = new javax.swing.GroupLayout(taxDetailsPanel2);
        taxDetailsPanel2.setLayout(taxDetailsPanel2Layout);
        taxDetailsPanel2Layout.setHorizontalGroup(
            taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gstInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceSerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gstInValue, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxComboOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceSeriaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(transportModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(placeSupplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleNoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transportModeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplyPlaceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        taxDetailsPanel2Layout.setVerticalGroup(
            taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxComboOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceSeriaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceSerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel)
                            .addComponent(gstInValue)
                            .addComponent(transportModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportModeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleNoValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(vehicleNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supplyPlaceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                                .addComponent(placeSupplyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                                .addGap(7, 7, 7)))))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        deliveryDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        recieverDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        recieverDetailsLabel.setText("Details of Receiver (Billed to)");

        receiverNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverNameLabel.setText("Name :");

        consigneelabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        consigneelabel.setText("Name :");

        consigneeDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        consigneeDetailsLabel.setText("Details of Consignee(Shipped to)");

        consigneeAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        consigneeAddressLabel.setText("Address :");

        consigneeNamevalue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        consigneeNamevalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consigneeNamevalueActionPerformed(evt);
            }
        });

        consigneeAddressValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        consigneeAddressValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        receiverAddressLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverAddressLabel.setText("Address :");

        receiverStatelabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverStatelabel.setText("State & Code : ");

        receiverNameValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        receiverNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverNameValueActionPerformed(evt);
            }
        });

        receiverAddressvalue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        receiverAddressvalue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverAddressvalueActionPerformed(evt);
            }
        });

        consigneeStateLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        consigneeStateLabel.setText("State  & Code :");

        consigneeStatevalue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        consigneeStatevalue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        receiverStateValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        receiverStateValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverStateValueActionPerformed(evt);
            }
        });

        receiverMobileLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverMobileLabel.setText("Mobile No :");

        receiverMobileValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        receiverMobileValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverMobileValueActionPerformed(evt);
            }
        });

        consigneeMobileValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        consigneeMobileValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        consigneeMobilelabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        consigneeMobilelabel.setText("Mobile no  :");

        receiverEmailValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        receiverEmailValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverEmailValueActionPerformed(evt);
            }
        });

        receiverEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverEmailLabel.setText("E-mail ID :");

        consigneeEmailValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        consigneeEmailValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        consigneeEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        consigneeEmailLabel.setText("E-mail ID :");

        receiverGSTLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverGSTLabel.setText("GSTIN/Unique :");

        consigneeGSTLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        consigneeGSTLabel.setText("GSTIN/Unique :");

        receiverGSTValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        receiverGSTValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiverGSTValueActionPerformed(evt);
            }
        });

        consigneeGSTValue.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        consigneeGSTValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AddProductPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        productNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productNameLabel.setText("Product Name ");

        productName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        productHSNCodeLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productHSNCodeLabel.setText("HSN Code ");

        productHsnCodeValue.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        productRateLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productRateLabel.setText("Rate ");

        productyQuantityValue.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productyQuantityValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productyQuantityValueActionPerformed(evt);
            }
        });

        productRateValue.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        productQuantityLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productQuantityLabel.setText("Quantity");

        addProductButton.setBackground(new java.awt.Color(0, 204, 204));
        addProductButton.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        addProductButton.setText("Add");
        addProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddProductPanelLayout = new javax.swing.GroupLayout(AddProductPanel);
        AddProductPanel.setLayout(AddProductPanelLayout);
        AddProductPanelLayout.setHorizontalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productNameLabel)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productHSNCodeLabel)
                    .addComponent(productHsnCodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productQuantityLabel)
                    .addComponent(productyQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productRateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddProductPanelLayout.createSequentialGroup()
                        .addComponent(productRateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addProductButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddProductPanelLayout.setVerticalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AddProductPanelLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(productRateLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(productyQuantityValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(productRateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addProductButton))))
                        .addComponent(productQuantityLabel))
                    .addGroup(AddProductPanelLayout.createSequentialGroup()
                        .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productHSNCodeLabel)
                            .addComponent(productNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productHsnCodeValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dtm=new javax.swing.table.DefaultTableModel();

        String[] headers=         new String [] {
            "Product Name", "HSN Code", "Quantity", "Rate","Total"
        };
        dtm.setColumnIdentifiers(headers);
        productTable.setModel(dtm);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setResizable(false);
            productTable.getColumnModel().getColumn(1).setResizable(false);
            productTable.getColumnModel().getColumn(2).setResizable(false);
            productTable.getColumnModel().getColumn(3).setResizable(false);
        }
        productTable.setModel(dtm);
        productTableScroll.setViewportView(productTable);

        javax.swing.GroupLayout deliveryDetailsPanelLayout = new javax.swing.GroupLayout(deliveryDetailsPanel);
        deliveryDetailsPanel.setLayout(deliveryDetailsPanelLayout);
        deliveryDetailsPanelLayout.setHorizontalGroup(
            deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(productTableScroll)
                    .addComponent(AddProductPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(receiverAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(receiverAddressvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(receiverNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                    .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(receiverStatelabel)
                                        .addComponent(receiverMobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(receiverMobileValue)
                                        .addComponent(receiverEmailValue)
                                        .addComponent(receiverStateValue, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(recieverDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(receiverEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addComponent(receiverGSTLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(receiverGSTValue, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(consigneeEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))
                                    .addComponent(consigneeGSTLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(consigneeEmailValue, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(consigneeGSTValue, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(consigneeDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(consigneelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(consigneeAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(consigneeNamevalue)
                                    .addComponent(consigneeAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(consigneeMobilelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(25, 25, 25)
                                    .addComponent(consigneeMobileValue, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                    .addComponent(consigneeStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(consigneeStatevalue))))))
                .addGap(4, 4, 4))
        );
        deliveryDetailsPanelLayout.setVerticalGroup(
            deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(recieverDetailsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiverNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverAddressvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiverAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(consigneeDetailsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consigneelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consigneeNamevalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consigneeAddressValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consigneeAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverStateValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiverStatelabel))
                        .addGap(10, 10, 10)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverMobileLabel)
                            .addComponent(receiverMobileValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverEmailLabel)
                            .addComponent(receiverEmailValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverGSTValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receiverGSTLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consigneeStateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consigneeStatevalue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addComponent(consigneeMobileValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(consigneeMobilelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(consigneeEmailValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(consigneeEmailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(consigneeGSTLabel)
                            .addComponent(consigneeGSTValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)))
                .addComponent(AddProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productTableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        footerPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Terms and Conditions : -");

        jLabel19.setText("* Any compalint about the consignement must be made within 7 days.");

        jLabel20.setText("* Our responsibility cease once goods leave out godown");

        jLabel21.setText("* Payment by bank drafts /NEFT / RTGS / CHEQUE");

        jLabel22.setText("* Payment must be made within 30 days.");

        jLabel23.setText("*24% interest will be charged after due date.");

        jLabel24.setText("* Subject to Delhi Jurisdiction only.");

        jLabel25.setText("Electronic Reference Number");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("FOR Happy Flower");

        jLabel27.setText("Authorised Signatory");

        jLabel28.setText("Name : ");

        jLabel29.setText("Designation : ");

        javax.swing.GroupLayout footerPanel1Layout = new javax.swing.GroupLayout(footerPanel1);
        footerPanel1.setLayout(footerPanel1Layout);
        footerPanel1Layout.setHorizontalGroup(
            footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel25)
                        .addComponent(jLabel26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanel1Layout.createSequentialGroup()
                        .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28))
                        .addGap(78, 78, 78)))
                .addGap(147, 147, 147)
                .addComponent(jLabel27)
                .addGap(108, 108, 108))
        );
        footerPanel1Layout.setVerticalGroup(
            footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addGap(41, 41, 41))
                        .addGroup(footerPanel1Layout.createSequentialGroup()
                            .addGroup(footerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(footerPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel26)
                                    .addGap(64, 64, 64))
                                .addComponent(jLabel28))
                            .addComponent(jLabel29)))
                    .addGroup(footerPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel24)))
                .addGap(21, 21, 21))
        );

        freightLabel.setText("Freight");

        freighValueLabel.setText("0");

        totalLabel.setText("Total");

        totalValueLabel.setText("0");

        CGSTValueLabel.setText("0");

        CGSTLabel.setText("CGST @ ... %");

        SGSTValueLabel.setText("0");

        SGSTLabel.setText("SGST @ ... %");

        IGSTValueLabel.setText("0");

        IGSTLabel.setText("IGST @ ... %");

        grandTotalValueLabel.setText("0");

        grandTotalLabel.setText("Grand Total");

        cgstTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cgstTextFieldActionPerformed(evt);
            }
        });

        SGSTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SGSTTextFieldActionPerformed(evt);
            }
        });

        IGSTTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IGSTTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout taxCalculationPanelLayout = new javax.swing.GroupLayout(taxCalculationPanel);
        taxCalculationPanel.setLayout(taxCalculationPanelLayout);
        taxCalculationPanelLayout.setHorizontalGroup(
            taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taxCalculationPanelLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxCalculationPanelLayout.createSequentialGroup()
                        .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CGSTLabel)
                            .addComponent(SGSTLabel)
                            .addComponent(IGSTLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cgstTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(IGSTTextField)
                            .addComponent(SGSTTextField))
                        .addGap(61, 61, 61))
                    .addGroup(taxCalculationPanelLayout.createSequentialGroup()
                        .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grandTotalLabel)
                            .addComponent(freightLabel)
                            .addComponent(totalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(taxCalculationPanelLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(SGSTValueLabel))
                        .addGroup(taxCalculationPanelLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(CGSTValueLabel))
                        .addGroup(taxCalculationPanelLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(freighValueLabel))
                        .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(grandTotalValueLabel)
                            .addComponent(IGSTValueLabel)))
                    .addGroup(taxCalculationPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(totalValueLabel)))
                .addGap(47, 47, 47))
        );
        taxCalculationPanelLayout.setVerticalGroup(
            taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxCalculationPanelLayout.createSequentialGroup()
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freightLabel)
                    .addComponent(freighValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(totalValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CGSTLabel)
                    .addComponent(CGSTValueLabel)
                    .addComponent(cgstTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SGSTLabel)
                    .addComponent(SGSTValueLabel)
                    .addComponent(SGSTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IGSTLabel)
                    .addComponent(IGSTValueLabel)
                    .addComponent(IGSTTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(taxCalculationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grandTotalLabel)
                    .addComponent(grandTotalValueLabel)))
        );

        javax.swing.GroupLayout taxDetailsPanel1Layout = new javax.swing.GroupLayout(taxDetailsPanel1);
        taxDetailsPanel1.setLayout(taxDetailsPanel1Layout);
        taxDetailsPanel1Layout.setHorizontalGroup(
            taxDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel1Layout.createSequentialGroup()
                .addGroup(taxDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxDetailsPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(headerTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(taxDetailsPanel1Layout.createSequentialGroup()
                        .addGap(705, 705, 705)
                        .addComponent(taxCalculationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taxDetailsPanel1Layout.createSequentialGroup()
                .addComponent(footerPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taxDetailsPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(taxDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deliveryDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        taxDetailsPanel1Layout.setVerticalGroup(
            taxDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel1Layout.createSequentialGroup()
                .addComponent(headerTitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveryDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxCalculationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(footerPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(taxDetailsPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taxComboOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxComboOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxComboOptionActionPerformed

    private void vehicleNoValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoValueActionPerformed

    private void transportModeValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportModeValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportModeValueActionPerformed

    private void consigneeNamevalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consigneeNamevalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consigneeNamevalueActionPerformed

    private void receiverNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverNameValueActionPerformed

    private void receiverAddressvalueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverAddressvalueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverAddressvalueActionPerformed

    private void receiverStateValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverStateValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverStateValueActionPerformed

    private void receiverMobileValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverMobileValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverMobileValueActionPerformed

    private void receiverEmailValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverEmailValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverEmailValueActionPerformed

    private void receiverGSTValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiverGSTValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiverGSTValueActionPerformed

    private void productyQuantityValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productyQuantityValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productyQuantityValueActionPerformed

    private void addProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductButtonActionPerformed
        // TODO add your handling code here:
        Vector<Object> data = new Vector<Object>();
        data.add(productName.getText());
        data.add(productHsnCodeValue.getText());
        data.add(productyQuantityValue.getText());
        data.add(productRateValue.getText());
        int total = Integer.parseInt(productyQuantityValue.getText()) * Integer.parseInt(productRateValue.getText());
        data.add(total);
        dtm.addRow(data);
    }//GEN-LAST:event_addProductButtonActionPerformed

    private void cgstTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cgstTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cgstTextFieldActionPerformed

    private void SGSTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SGSTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SGSTTextFieldActionPerformed

    private void IGSTTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IGSTTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IGSTTextFieldActionPerformed

    private DefaultTableModel dtm;  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProductPanel;
    private javax.swing.JLabel CGSTLabel;
    private javax.swing.JLabel CGSTValueLabel;
    private javax.swing.JLabel IGSTLabel;
    private javax.swing.JTextField IGSTTextField;
    private javax.swing.JLabel IGSTValueLabel;
    private javax.swing.JLabel SGSTLabel;
    private javax.swing.JTextField SGSTTextField;
    private javax.swing.JLabel SGSTValueLabel;
    private javax.swing.JButton addProductButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField cgstTextField;
    private javax.swing.JLabel consigneeAddressLabel;
    private javax.swing.JTextField consigneeAddressValue;
    private javax.swing.JLabel consigneeDetailsLabel;
    private javax.swing.JLabel consigneeEmailLabel;
    private javax.swing.JTextField consigneeEmailValue;
    private javax.swing.JLabel consigneeGSTLabel;
    private javax.swing.JTextField consigneeGSTValue;
    private javax.swing.JTextField consigneeMobileValue;
    private javax.swing.JLabel consigneeMobilelabel;
    private javax.swing.JTextField consigneeNamevalue;
    private javax.swing.JLabel consigneeStateLabel;
    private javax.swing.JTextField consigneeStatevalue;
    private javax.swing.JLabel consigneelabel;
    private javax.swing.JPanel deliveryDetailsPanel;
    private javax.swing.JLabel emailLable;
    private javax.swing.JPanel footerPanel1;
    private javax.swing.JLabel freighValueLabel;
    private javax.swing.JLabel freightLabel;
    private javax.swing.JLabel grandTotalLabel;
    private javax.swing.JLabel grandTotalValueLabel;
    private javax.swing.JLabel gstInLabel;
    private javax.swing.JLabel gstInValue;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerTitlePanel;
    private javax.swing.JLabel invoiceSeriaValue;
    private javax.swing.JLabel invoiceSerialLabel;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobileLable;
    private javax.swing.JLabel placeSupplyLabel;
    private javax.swing.JLabel productHSNCodeLabel;
    private javax.swing.JTextField productHsnCodeValue;
    private javax.swing.JTextField productName;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel productQuantityLabel;
    private javax.swing.JLabel productRateLabel;
    private javax.swing.JTextField productRateValue;
    private javax.swing.JTable productTable;
    private javax.swing.JScrollPane productTableScroll;
    private javax.swing.JTextField productyQuantityValue;
    private javax.swing.JLabel receiverAddressLabel;
    private javax.swing.JTextField receiverAddressvalue;
    private javax.swing.JLabel receiverEmailLabel;
    private javax.swing.JTextField receiverEmailValue;
    private javax.swing.JLabel receiverGSTLabel;
    private javax.swing.JTextField receiverGSTValue;
    private javax.swing.JLabel receiverMobileLabel;
    private javax.swing.JTextField receiverMobileValue;
    private javax.swing.JLabel receiverNameLabel;
    private javax.swing.JTextField receiverNameValue;
    private javax.swing.JTextField receiverStateValue;
    private javax.swing.JLabel receiverStatelabel;
    private javax.swing.JLabel recieverDetailsLabel;
    private javax.swing.JTextField supplyPlaceValue;
    private javax.swing.JPanel taxCalculationPanel;
    private javax.swing.JLabel taxChargeLabel;
    private javax.swing.JComboBox<String> taxComboOption;
    private javax.swing.JPanel taxDetailsPanel1;
    private javax.swing.JPanel taxDetailsPanel2;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalValueLabel;
    private javax.swing.JLabel transportModeLabel;
    private javax.swing.JTextField transportModeValue;
    private javax.swing.JLabel vehicleNoLabel;
    private javax.swing.JTextField vehicleNoValue;
    // End of variables declaration//GEN-END:variables
}
