/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.swingExample;

import com.java.main.*;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhi
 */
public class BillChallanFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalBillChallan
     */
    public BillChallanFrame() {
        initComponents();
        setSize(700, 650); 
	setLocation(300, 20);
        setClosable(true); 
        setIconifiable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        billChallanPane = new javax.swing.JScrollPane();
        billChallanPanel = new javax.swing.JPanel();
        companyDetailsLabel = new javax.swing.JPanel();
        landlineLabel = new javax.swing.JLabel();
        websiteLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        logoPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        orderLabel = new javax.swing.JLabel();
        orderNoTextField = new javax.swing.JTextField();
        receiverDetailsLabel = new javax.swing.JLabel();
        mrLabel = new javax.swing.JLabel();
        mrMissTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        addressLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTextField1 = new javax.swing.JTextField();
        productsLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        senderDetailsLabel = new javax.swing.JLabel();
        senderDetailsTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateLabel1 = new javax.swing.JLabel();
        dateTextField1 = new javax.swing.JTextField();
        orderLabel1 = new javax.swing.JLabel();
        orderNoTextField1 = new javax.swing.JTextField();
        mrMissTextField1 = new javax.swing.JTextField();
        mrLabel1 = new javax.swing.JLabel();
        addressLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        addressTextArea2 = new javax.swing.JTextArea();
        thankYouNoteLabel = new javax.swing.JLabel();
        messageLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        addressTextArea1 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        productNameLabel = new javax.swing.JLabel();
        productList = new javax.swing.JComboBox<>();
        addProductBtn = new javax.swing.JButton();
        pLabel1 = new javax.swing.JLabel();
        p2Label = new javax.swing.JLabel();
        p3Label = new javax.swing.JLabel();
        p4Label = new javax.swing.JLabel();
        p5Label = new javax.swing.JLabel();
        p6Label = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        printBtn = new javax.swing.JButton();

        landlineLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        landlineLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        landlineLabel.setText("011-2458967");
        landlineLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        websiteLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        websiteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        websiteLabel.setText("www.happyflowers.com");
        websiteLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailLabel.setText("happyflowers@gmail.com");
        emailLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mobile");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Landline");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Website");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email Id");

        mobileLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobileLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobileLabel.setText("9999633345");
        mobileLabel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout companyDetailsLabelLayout = new javax.swing.GroupLayout(companyDetailsLabel);
        companyDetailsLabel.setLayout(companyDetailsLabelLayout);
        companyDetailsLabelLayout.setHorizontalGroup(
            companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, companyDetailsLabelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landlineLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(websiteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        companyDetailsLabelLayout.setVerticalGroup(
            companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyDetailsLabelLayout.createSequentialGroup()
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(mobileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(landlineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(websiteLabel)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyDetailsLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)))
        );

        logoPanel.setToolTipText("Uploaded Logo Image");
        logoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        headerLabel.setFont(new java.awt.Font("Lucida Handwriting", 1, 16)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 51, 51));
        headerLabel.setText("24X7 Flowers,Cakes & Gifts Services in India & Around the World.");
        headerLabel.setAlignmentX(20.0F);

        dateLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLabel.setText("Date");

        orderLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderLabel.setText("Order No");

        receiverDetailsLabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        receiverDetailsLabel.setText("Receiver Details");

        mrLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mrLabel.setText("Mr. /Mrs. Miss");

        addressTextArea.setColumns(20);
        addressTextArea.setRows(5);
        jScrollPane2.setViewportView(addressTextArea);

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressLabel.setText("Address");

        telephoneLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        telephoneLabel.setText("Telephone");

        telephoneTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneTextField1ActionPerformed(evt);
            }
        });

        productsLabel.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        productsLabel.setText("Products Details");

        messageLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messageLabel.setText("Message");

        senderDetailsLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        senderDetailsLabel.setText("Sender Details");

        senderDetailsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderDetailsTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Spreading Happiness on Plant Earth with flowers");

        dateLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dateLabel1.setText("Date");

        dateTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextField1ActionPerformed(evt);
            }
        });

        orderLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderLabel1.setText("Order No");

        mrLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mrLabel1.setText("Mr. /Mrs. Miss");

        addressLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addressLabel1.setText("Address");

        addressTextArea2.setColumns(20);
        addressTextArea2.setRows(5);
        jScrollPane3.setViewportView(addressTextArea2);

        thankYouNoteLabel.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        thankYouNoteLabel.setForeground(new java.awt.Color(255, 51, 51));
        thankYouNoteLabel.setText("Thanking You Note");

        messageLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        messageLabel1.setText("Message");

        addressTextArea1.setColumns(20);
        addressTextArea1.setRows(5);
        jScrollPane5.setViewportView(addressTextArea1);

        productNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productNameLabel.setText("Product Name");

        productList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        productList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cake", "Chocolate", "Flower", "Gift Items" }));

        addProductBtn.setBackground(new java.awt.Color(51, 51, 255));
        addProductBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addProductBtn.setText("Add");

        pLabel1.setText("P1");

        p2Label.setText("P2");

        p3Label.setText("p3");

        p4Label.setText("p4");

        p5Label.setText("p5");

        p6Label.setText("p6");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exitBtn.setText("EXIT");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveBtn.setText("SAVE");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        printBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        printBtn.setText("PRINT");
        printBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printBtnMouseClicked(evt);
            }
        });
        printBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122)
                .addComponent(printBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(saveBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(exitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout billChallanPanelLayout = new javax.swing.GroupLayout(billChallanPanel);
        billChallanPanel.setLayout(billChallanPanelLayout);
        billChallanPanelLayout.setHorizontalGroup(
            billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billChallanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(companyDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, billChallanPanelLayout.createSequentialGroup()
                                        .addGap(278, 278, 278)
                                        .addComponent(productsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, billChallanPanelLayout.createSequentialGroup()
                                        .addComponent(productNameLabel)
                                        .addGap(18, 18, 18)
                                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                                .addComponent(productList, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(addProductBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(pLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                                    .addComponent(p4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(p2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                                    .addComponent(p5Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(p6Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dateLabel)
                                            .addComponent(telephoneLabel))
                                        .addGap(18, 18, 18)
                                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(telephoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(orderLabel)
                                                .addGap(18, 18, 18)
                                                .addComponent(orderNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(mrMissTextField)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(billChallanPanelLayout.createSequentialGroup()
                                            .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(senderDetailsLabel)
                                                .addComponent(messageLabel))
                                            .addGap(18, 18, 18)
                                            .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(senderDetailsTextField)
                                                .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createSequentialGroup()
                                            .addComponent(dateLabel1)
                                            .addGap(77, 77, 77)
                                            .addComponent(dateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(80, 80, 80)
                                            .addComponent(orderLabel1)
                                            .addGap(18, 18, 18)
                                            .addComponent(orderNoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mrLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addressLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(messageLabel1))
                                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(mrMissTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(billChallanPanelLayout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(thankYouNoteLabel))))
                                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(receiverDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        billChallanPanelLayout.setVerticalGroup(
            billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(billChallanPanelLayout.createSequentialGroup()
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(companyDetailsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(headerLabel)
                .addGap(13, 13, 13)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderLabel)
                        .addComponent(orderNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLabel))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(receiverDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addComponent(mrLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addComponent(mrMissTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(telephoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telephoneLabel))
                .addGap(1, 1, 1)
                .addComponent(productsLabel)
                .addGap(1, 1, 1)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productNameLabel)
                    .addComponent(productList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProductBtn))
                .addGap(18, 18, 18)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pLabel1)
                    .addComponent(p2Label)
                    .addComponent(p3Label))
                .addGap(18, 18, 18)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4Label)
                    .addComponent(p5Label)
                    .addComponent(p6Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senderDetailsLabel)
                    .addComponent(senderDetailsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createSequentialGroup()
                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLabel1)
                            .addComponent(orderLabel1)
                            .addComponent(orderNoTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mrMissTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mrLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thankYouNoteLabel))
                    .addComponent(addressLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(billChallanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(billChallanPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(messageLabel1)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billChallanPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        billChallanPane.setViewportView(billChallanPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billChallanPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billChallanPane, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telephoneTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneTextField1ActionPerformed

    private void senderDetailsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderDetailsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senderDetailsTextFieldActionPerformed

    private void dateTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextField1ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        try
        {

            pst=con.prepareStatement("insert into Customer_Master values(?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,""+id.getText());
            pst.setString(2,""+name.getText());
            pst.setString(3,""+add1.getText());
            pst.setString(4,""+add2.getText());
            pst.setString(5,""+add3.getText());
            pst.setString(6,""+tel.getText());
            pst.setString(7,""+eid.getText());
            pst.setString(8,""+cst.getText());
            pst.setString(9,""+tin.getText());
            pst.setString(10,""+stex.getText());
            saveBtn.setEnabled(true);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Record Inserted Sucessfully....");

            id.setText("");
            name.setText("");
            add1.setText("");
            add2.setText("");
            add3.setText("");
            eid.setText("");
            cst.setText("");

            tel.setText("");
            tin.setText("");
            stex.setText("");
            con.close();

            con=re.getCon();

            rs=st.executeQuery("select max(Customer_no)from Customer_Master");

            rs.next();
            if(rs!=null)
            {
                i_no=rs.getInt(1);
                i_no++;
            }
            else
            i_no=1;

            id.setText(""+i_no);
    }//GEN-LAST:event_saveBtnActionPerformed

    private void printBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printBtnMouseClicked

    }//GEN-LAST:event_printBtnMouseClicked

    private void printBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBtnActionPerformed

        EditCustomer ec;
        try {
            ec = new EditCustomer();
            JDesktopPane p=getDesktopPane();
            p.add(ec);
            ec.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(mainform.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(mainform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProductBtn;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JTextArea addressTextArea1;
    private javax.swing.JTextArea addressTextArea2;
    private javax.swing.JScrollPane billChallanPane;
    private javax.swing.JPanel billChallanPanel;
    private javax.swing.JPanel companyDetailsLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateLabel1;
    private javax.swing.JTextField dateTextField1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel headerLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel landlineLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JLabel mrLabel;
    private javax.swing.JLabel mrLabel1;
    private javax.swing.JTextField mrMissTextField;
    private javax.swing.JTextField mrMissTextField1;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JLabel orderLabel1;
    private javax.swing.JTextField orderNoTextField;
    private javax.swing.JTextField orderNoTextField1;
    private javax.swing.JLabel p2Label;
    private javax.swing.JLabel p3Label;
    private javax.swing.JLabel p4Label;
    private javax.swing.JLabel p5Label;
    private javax.swing.JLabel p6Label;
    private javax.swing.JLabel pLabel1;
    private javax.swing.JButton printBtn;
    private javax.swing.JComboBox<String> productList;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel productsLabel;
    private javax.swing.JLabel receiverDetailsLabel;
    private javax.swing.JButton saveBtn;
    private javax.swing.JLabel senderDetailsLabel;
    private javax.swing.JTextField senderDetailsTextField;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextField;
    private javax.swing.JTextField telephoneTextField1;
    private javax.swing.JTextField telephoneTextField2;
    private javax.swing.JLabel thankYouNoteLabel;
    private javax.swing.JLabel websiteLabel;
    // End of variables declaration//GEN-END:variables
}
