/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.swingExample;

import com.java.main.TaxInvoice;

/**
 *
 * @author Keshav
 */
public class TaxInvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form TaxInvoicePanel
     */
    public TaxInvoicePanel() {
        initComponents();
       
    }
    
      public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaxInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
          System.out.println("swingtable.TaxInvoicePanel.main()");

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                System.out.println("swingtable.TaxInvoicePanel.main()");
                new TaxInvoicePanel().setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        mobileLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        taxDetailsPanel = new javax.swing.JPanel();
        gstInLabel = new javax.swing.JLabel();
        gstInValue = new javax.swing.JLabel();
        taxChargeLabel = new javax.swing.JLabel();
        taxComboOption = new javax.swing.JComboBox<>();
        invoiceSerialLabel = new javax.swing.JLabel();
        vehicleNoLabel = new javax.swing.JLabel();
        transportModeLabel = new javax.swing.JLabel();
        placeSupplyLabel = new javax.swing.JLabel();
        vehicleNoText = new javax.swing.JTextField();
        transportModeText = new javax.swing.JTextField();
        supplyPlaceText = new javax.swing.JTextField();
        invoiceSerialLabel1 = new javax.swing.JLabel();
        AddProductPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        deliveryDetailsPanel = new javax.swing.JPanel();
        recieverDetailsLabel = new javax.swing.JLabel();
        receiverNameLabel = new javax.swing.JLabel();
        vehicleNoLabel1 = new javax.swing.JLabel();
        transportModeLabel1 = new javax.swing.JLabel();
        placeSupplyLabel1 = new javax.swing.JLabel();
        vehicleNoText1 = new javax.swing.JTextField();
        supplyPlaceText1 = new javax.swing.JTextField();
        invoiceSerialLabel3 = new javax.swing.JLabel();
        gstInLabel2 = new javax.swing.JLabel();
        vehicleNoText2 = new javax.swing.JTextField();
        vehicleNoText3 = new javax.swing.JTextField();
        placeSupplyLabel2 = new javax.swing.JLabel();
        supplyPlaceText2 = new javax.swing.JTextField();
        vehicleNoText4 = new javax.swing.JTextField();
        gstInLabel3 = new javax.swing.JLabel();
        vehicleNoText5 = new javax.swing.JTextField();
        supplyPlaceText3 = new javax.swing.JTextField();
        placeSupplyLabel3 = new javax.swing.JLabel();
        vehicleNoText6 = new javax.swing.JTextField();
        gstInLabel4 = new javax.swing.JLabel();
        supplyPlaceText4 = new javax.swing.JTextField();
        gstInLabel5 = new javax.swing.JLabel();
        gstInLabel6 = new javax.swing.JLabel();
        gstInLabel7 = new javax.swing.JLabel();
        vehicleNoText7 = new javax.swing.JTextField();
        supplyPlaceText5 = new javax.swing.JTextField();
        ProductListTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setName(""); // NOI18N

        headerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        headerLabel.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 51, 51));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Happy Flower1");
        headerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("A-24 , Ganesh Nagar, Pandav Nagar Complex,Delhi-92");
        addressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mobileLable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mobileLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobileLable.setText("Email : florishtth@gmail.com");
        mobileLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mob : 9999633345,8800675678");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(headerPanelLayout.createSequentialGroup()
                            .addComponent(mobileLable, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(156, 156, 156))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(mobileLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        taxDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gstInLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel.setText("GSTIN Number   :");

        gstInValue.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInValue.setText("HJVGHFGFAHJHJD");

        taxChargeLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        taxChargeLabel.setText("Tax is on Reverse Charge  :");

        taxComboOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        taxComboOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxComboOptionActionPerformed(evt);
            }
        });

        invoiceSerialLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSerialLabel.setText("FLGJJGD54554");

        vehicleNoLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        vehicleNoLabel.setText("Vehicle No :");

        transportModeLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        transportModeLabel.setText("Transport Mode   :");

        placeSupplyLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel.setText("Place of Supply : ");

        vehicleNoText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoTextActionPerformed(evt);
            }
        });

        transportModeText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        transportModeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportModeTextActionPerformed(evt);
            }
        });

        supplyPlaceText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        invoiceSerialLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSerialLabel1.setText("Invoice Serial No : ");

        javax.swing.GroupLayout taxDetailsPanelLayout = new javax.swing.GroupLayout(taxDetailsPanel);
        taxDetailsPanel.setLayout(taxDetailsPanelLayout);
        taxDetailsPanelLayout.setHorizontalGroup(
            taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gstInLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceSerialLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gstInValue, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxComboOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceSerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(transportModeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vehicleNoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(placeSupplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transportModeText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplyPlaceText, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        taxDetailsPanelLayout.setVerticalGroup(
            taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxDetailsPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxChargeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxComboOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceSerialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceSerialLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(taxDetailsPanelLayout.createSequentialGroup()
                        .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel)
                            .addComponent(gstInValue)
                            .addComponent(transportModeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportModeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taxDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeSupplyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyPlaceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AddProductPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Product Name ");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("HSN Code ");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Rate ");

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Quantity");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddProductPanelLayout = new javax.swing.GroupLayout(AddProductPanel);
        AddProductPanel.setLayout(AddProductPanelLayout);
        AddProductPanelLayout.setHorizontalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddProductPanelLayout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton1)))
                .addGap(27, 27, 27))
        );
        AddProductPanelLayout.setVerticalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        deliveryDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        recieverDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        recieverDetailsLabel.setText("Details of Receiver (Billed to)");

        receiverNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverNameLabel.setText("Name :");

        vehicleNoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        vehicleNoLabel1.setText("Name :");

        transportModeLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        transportModeLabel1.setText("Details of Consignee(Shipped to)");

        placeSupplyLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel1.setText("Address :");

        vehicleNoText1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText1ActionPerformed(evt);
            }
        });

        supplyPlaceText1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        invoiceSerialLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSerialLabel3.setText("Address :");

        gstInLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel2.setText("State & Code : ");

        vehicleNoText2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText2ActionPerformed(evt);
            }
        });

        vehicleNoText3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText3ActionPerformed(evt);
            }
        });

        placeSupplyLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel2.setText("State  & Code :");

        supplyPlaceText2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        vehicleNoText4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText4ActionPerformed(evt);
            }
        });

        gstInLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel3.setText("Mobile No :");

        vehicleNoText5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText5ActionPerformed(evt);
            }
        });

        supplyPlaceText3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        placeSupplyLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel3.setText("Mobile no  :");

        vehicleNoText6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText6ActionPerformed(evt);
            }
        });

        gstInLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel4.setText("E-mail ID :");

        supplyPlaceText4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gstInLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel5.setText("E-mail ID :");

        gstInLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel6.setText("GSTIN/Unique :");

        gstInLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel7.setText("GSTIN/Unique :");

        vehicleNoText7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText7ActionPerformed(evt);
            }
        });

        supplyPlaceText5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout deliveryDetailsPanelLayout = new javax.swing.GroupLayout(deliveryDetailsPanel);
        deliveryDetailsPanel.setLayout(deliveryDetailsPanelLayout);
        deliveryDetailsPanelLayout.setHorizontalGroup(
            deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deliveryDetailsPanelLayout.createSequentialGroup()
                                .addComponent(invoiceSerialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vehicleNoText3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deliveryDetailsPanelLayout.createSequentialGroup()
                                .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vehicleNoText2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                            .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gstInLabel2)
                                .addComponent(gstInLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vehicleNoText5, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                .addComponent(vehicleNoText6)
                                .addComponent(vehicleNoText4)))
                        .addComponent(recieverDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gstInLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addComponent(gstInLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(vehicleNoText7, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(placeSupplyLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(gstInLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(15, 15, 15))
                            .addComponent(gstInLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(supplyPlaceText4, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(supplyPlaceText3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(supplyPlaceText5))))
                    .addComponent(transportModeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleNoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeSupplyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeSupplyLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vehicleNoText1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(supplyPlaceText2)
                            .addComponent(supplyPlaceText1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deliveryDetailsPanelLayout.setVerticalGroup(
            deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(recieverDetailsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleNoText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceSerialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addComponent(transportModeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleNoText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplyPlaceText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeSupplyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeSupplyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyPlaceText2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeSupplyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyPlaceText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplyPlaceText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstInLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel7)
                            .addComponent(supplyPlaceText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstInLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel3)
                            .addComponent(vehicleNoText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel4)
                            .addComponent(vehicleNoText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoText7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstInLabel6))))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ProductListTable.setViewportView(jTable1);

        jLabel6.setText("dfsfj,ds,");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(342, 342, 342))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(taxDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deliveryDetailsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProductListTable))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveryDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(ProductListTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void vehicleNoText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText1ActionPerformed

    private void vehicleNoText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText2ActionPerformed

    private void vehicleNoText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText3ActionPerformed

    private void vehicleNoText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText4ActionPerformed

    private void vehicleNoText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText5ActionPerformed

    private void vehicleNoText6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText6ActionPerformed

    private void vehicleNoText7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText7ActionPerformed

    private void vehicleNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoTextActionPerformed

    private void transportModeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportModeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportModeTextActionPerformed

    private void taxComboOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxComboOptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxComboOptionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProductPanel;
    private javax.swing.JScrollPane ProductListTable;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel deliveryDetailsPanel;
    private javax.swing.JLabel gstInLabel;
    private javax.swing.JLabel gstInLabel2;
    private javax.swing.JLabel gstInLabel3;
    private javax.swing.JLabel gstInLabel4;
    private javax.swing.JLabel gstInLabel5;
    private javax.swing.JLabel gstInLabel6;
    private javax.swing.JLabel gstInLabel7;
    private javax.swing.JLabel gstInValue;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel invoiceSerialLabel;
    private javax.swing.JLabel invoiceSerialLabel1;
    private javax.swing.JLabel invoiceSerialLabel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel mobileLable;
    private javax.swing.JLabel placeSupplyLabel;
    private javax.swing.JLabel placeSupplyLabel1;
    private javax.swing.JLabel placeSupplyLabel2;
    private javax.swing.JLabel placeSupplyLabel3;
    private javax.swing.JLabel receiverNameLabel;
    private javax.swing.JLabel recieverDetailsLabel;
    private javax.swing.JTextField supplyPlaceText;
    private javax.swing.JTextField supplyPlaceText1;
    private javax.swing.JTextField supplyPlaceText2;
    private javax.swing.JTextField supplyPlaceText3;
    private javax.swing.JTextField supplyPlaceText4;
    private javax.swing.JTextField supplyPlaceText5;
    private javax.swing.JLabel taxChargeLabel;
    private javax.swing.JComboBox<String> taxComboOption;
    private javax.swing.JPanel taxDetailsPanel;
    private javax.swing.JLabel transportModeLabel;
    private javax.swing.JLabel transportModeLabel1;
    private javax.swing.JTextField transportModeText;
    private javax.swing.JLabel vehicleNoLabel;
    private javax.swing.JLabel vehicleNoLabel1;
    private javax.swing.JTextField vehicleNoText;
    private javax.swing.JTextField vehicleNoText1;
    private javax.swing.JTextField vehicleNoText2;
    private javax.swing.JTextField vehicleNoText3;
    private javax.swing.JTextField vehicleNoText4;
    private javax.swing.JTextField vehicleNoText5;
    private javax.swing.JTextField vehicleNoText6;
    private javax.swing.JTextField vehicleNoText7;
    // End of variables declaration//GEN-END:variables
}
