/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.swingExample;

/**
 *
 * @author Abhi
 */
public class TaxInvoiceInternal extends javax.swing.JInternalFrame {

    /**
     * Creates new form TaxInvoiceInternal
     */
    public TaxInvoiceInternal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taxDetailsPanel1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        mobileLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        taxDetailsPanel2 = new javax.swing.JPanel();
        gstInLabel2 = new javax.swing.JLabel();
        gstInValue2 = new javax.swing.JLabel();
        taxChargeLabel2 = new javax.swing.JLabel();
        taxComboOption2 = new javax.swing.JComboBox<>();
        invoiceSerialLabel4 = new javax.swing.JLabel();
        vehicleNoLabel2 = new javax.swing.JLabel();
        transportModeLabel2 = new javax.swing.JLabel();
        placeSupplyLabel2 = new javax.swing.JLabel();
        vehicleNoText2 = new javax.swing.JTextField();
        transportModeText2 = new javax.swing.JTextField();
        supplyPlaceText2 = new javax.swing.JTextField();
        invoiceSerialLabel5 = new javax.swing.JLabel();
        deliveryDetailsPanel = new javax.swing.JPanel();
        recieverDetailsLabel = new javax.swing.JLabel();
        receiverNameLabel = new javax.swing.JLabel();
        vehicleNoLabel1 = new javax.swing.JLabel();
        transportModeLabel1 = new javax.swing.JLabel();
        placeSupplyLabel1 = new javax.swing.JLabel();
        vehicleNoText1 = new javax.swing.JTextField();
        supplyPlaceText1 = new javax.swing.JTextField();
        invoiceSerialLabel3 = new javax.swing.JLabel();
        gstInLabel3 = new javax.swing.JLabel();
        vehicleNoText3 = new javax.swing.JTextField();
        vehicleNoText4 = new javax.swing.JTextField();
        placeSupplyLabel3 = new javax.swing.JLabel();
        supplyPlaceText3 = new javax.swing.JTextField();
        vehicleNoText5 = new javax.swing.JTextField();
        gstInLabel4 = new javax.swing.JLabel();
        vehicleNoText6 = new javax.swing.JTextField();
        supplyPlaceText4 = new javax.swing.JTextField();
        placeSupplyLabel4 = new javax.swing.JLabel();
        vehicleNoText7 = new javax.swing.JTextField();
        gstInLabel5 = new javax.swing.JLabel();
        supplyPlaceText5 = new javax.swing.JTextField();
        gstInLabel6 = new javax.swing.JLabel();
        gstInLabel7 = new javax.swing.JLabel();
        gstInLabel8 = new javax.swing.JLabel();
        vehicleNoText8 = new javax.swing.JTextField();
        supplyPlaceText6 = new javax.swing.JTextField();
        AddProductPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hsnCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productyQuantity = new javax.swing.JTextField();
        productRate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        taxDetailsPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        headerLabel.setFont(new java.awt.Font("Pristina", 1, 48)); // NOI18N
        headerLabel.setForeground(new java.awt.Color(255, 51, 51));
        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setText("Happy Flower1");
        headerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addressLabel.setText("A-24 , Ganesh Nagar, Pandav Nagar Complex,Delhi-92");
        addressLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        mobileLable.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        mobileLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mobileLable.setText("Email : florishtth@gmail.com");
        mobileLable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mob : 9999633345,8800675678");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mobileLable, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(156, 156, 156)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(mobileLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        taxDetailsPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gstInLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel2.setText("GSTIN Number   :");

        gstInValue2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInValue2.setText("HJVGHFGFAHJHJD");

        taxChargeLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        taxChargeLabel2.setText("Tax is on Reverse Charge  :");

        taxComboOption2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        taxComboOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taxComboOption2ActionPerformed(evt);
            }
        });

        invoiceSerialLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSerialLabel4.setText("FLGJJGD54554");

        vehicleNoLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        vehicleNoLabel2.setText("Vehicle No :");

        transportModeLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        transportModeLabel2.setText("Transport Mode   :");

        placeSupplyLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel2.setText("Place of Supply : ");

        vehicleNoText2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText2ActionPerformed(evt);
            }
        });

        transportModeText2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        transportModeText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transportModeText2ActionPerformed(evt);
            }
        });

        supplyPlaceText2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        invoiceSerialLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSerialLabel5.setText("Invoice Serial No : ");

        javax.swing.GroupLayout taxDetailsPanel2Layout = new javax.swing.GroupLayout(taxDetailsPanel2);
        taxDetailsPanel2.setLayout(taxDetailsPanel2Layout);
        taxDetailsPanel2Layout.setHorizontalGroup(
            taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxChargeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gstInLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceSerialLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gstInValue2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taxComboOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceSerialLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(transportModeLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(vehicleNoLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(placeSupplyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(transportModeText2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleNoText2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplyPlaceText2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        taxDetailsPanel2Layout.setVerticalGroup(
            taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxChargeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxComboOption2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceSerialLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceSerialLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(taxDetailsPanel2Layout.createSequentialGroup()
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel2)
                            .addComponent(gstInValue2)
                            .addComponent(transportModeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transportModeText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleNoText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(taxDetailsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeSupplyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyPlaceText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        deliveryDetailsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        recieverDetailsLabel.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        recieverDetailsLabel.setText("Details of Receiver (Billed to)");

        receiverNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        receiverNameLabel.setText("Name :");

        vehicleNoLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        vehicleNoLabel1.setText("Name :");

        transportModeLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        transportModeLabel1.setText("Details of Consignee(Shipped to)");

        placeSupplyLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel1.setText("Address :");

        vehicleNoText1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText1ActionPerformed(evt);
            }
        });

        supplyPlaceText1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        invoiceSerialLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        invoiceSerialLabel3.setText("Address :");

        gstInLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel3.setText("State & Code : ");

        vehicleNoText3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText3ActionPerformed(evt);
            }
        });

        vehicleNoText4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText4ActionPerformed(evt);
            }
        });

        placeSupplyLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel3.setText("State  & Code :");

        supplyPlaceText3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        vehicleNoText5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText5ActionPerformed(evt);
            }
        });

        gstInLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel4.setText("Mobile No :");

        vehicleNoText6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText6ActionPerformed(evt);
            }
        });

        supplyPlaceText4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        placeSupplyLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        placeSupplyLabel4.setText("Mobile no  :");

        vehicleNoText7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText7ActionPerformed(evt);
            }
        });

        gstInLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel5.setText("E-mail ID :");

        supplyPlaceText5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        gstInLabel6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel6.setText("E-mail ID :");

        gstInLabel7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel7.setText("GSTIN/Unique :");

        gstInLabel8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        gstInLabel8.setText("GSTIN/Unique :");

        vehicleNoText8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        vehicleNoText8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleNoText8ActionPerformed(evt);
            }
        });

        supplyPlaceText6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        supplyPlaceText6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        AddProductPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Product Name ");

        productName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel3.setText("HSN Code ");

        hsnCode.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setText("Rate ");

        productyQuantity.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        productyQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productyQuantityActionPerformed(evt);
            }
        });

        productRate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel4.setText("Quantity");

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddProductPanelLayout = new javax.swing.GroupLayout(AddProductPanel);
        AddProductPanel.setLayout(AddProductPanelLayout);
        AddProductPanelLayout.setHorizontalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(hsnCode, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(productyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProductPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))
                    .addGroup(AddProductPanelLayout.createSequentialGroup()
                        .addComponent(productRate, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(32, 32, 32))))
        );
        AddProductPanelLayout.setVerticalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProductPanelLayout.createSequentialGroup()
                        .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hsnCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddProductPanelLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productyQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(productRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton1))))
                    .addComponent(jLabel4))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "HSN Code", "Quantity", "Rate", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        javax.swing.GroupLayout deliveryDetailsPanelLayout = new javax.swing.GroupLayout(deliveryDetailsPanel);
        deliveryDetailsPanel.setLayout(deliveryDetailsPanelLayout);
        deliveryDetailsPanelLayout.setHorizontalGroup(
            deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deliveryDetailsPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(invoiceSerialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(vehicleNoText4, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(vehicleNoText3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                    .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(gstInLabel3)
                                        .addComponent(gstInLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(vehicleNoText6, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                        .addComponent(vehicleNoText7)
                                        .addComponent(vehicleNoText5)))
                                .addComponent(recieverDetailsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gstInLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addComponent(gstInLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(vehicleNoText8, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(placeSupplyLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                            .addComponent(gstInLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(15, 15, 15))
                                    .addComponent(gstInLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(supplyPlaceText5, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(supplyPlaceText4, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(supplyPlaceText6))))
                            .addComponent(transportModeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicleNoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(placeSupplyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(placeSupplyLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vehicleNoText1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                    .addComponent(supplyPlaceText3)
                                    .addComponent(supplyPlaceText1)))))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addComponent(AddProductPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        deliveryDetailsPanelLayout.setVerticalGroup(
            deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(recieverDetailsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(receiverNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleNoText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceSerialLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addComponent(transportModeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleNoText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplyPlaceText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(placeSupplyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeSupplyLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyPlaceText3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placeSupplyLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplyPlaceText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supplyPlaceText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstInLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel8)
                            .addComponent(supplyPlaceText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(deliveryDetailsPanelLayout.createSequentialGroup()
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstInLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel4)
                            .addComponent(vehicleNoText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gstInLabel5)
                            .addComponent(vehicleNoText7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleNoText8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gstInLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(deliveryDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout taxDetailsPanel1Layout = new javax.swing.GroupLayout(taxDetailsPanel1);
        taxDetailsPanel1.setLayout(taxDetailsPanel1Layout);
        taxDetailsPanel1Layout.setHorizontalGroup(
            taxDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel1Layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(673, Short.MAX_VALUE))
            .addGroup(taxDetailsPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taxDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taxDetailsPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deliveryDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        taxDetailsPanel1Layout.setVerticalGroup(
            taxDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxDetailsPanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taxDetailsPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveryDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(taxDetailsPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taxComboOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taxComboOption2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taxComboOption2ActionPerformed

    private void vehicleNoText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText2ActionPerformed

    private void transportModeText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transportModeText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transportModeText2ActionPerformed

    private void vehicleNoText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText1ActionPerformed

    private void vehicleNoText3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText3ActionPerformed

    private void vehicleNoText4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText4ActionPerformed

    private void vehicleNoText5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText5ActionPerformed

    private void vehicleNoText6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText6ActionPerformed

    private void vehicleNoText7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText7ActionPerformed

    private void vehicleNoText8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleNoText8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicleNoText8ActionPerformed

    private void productyQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productyQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productyQuantityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        productName.getText();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddProductPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel deliveryDetailsPanel;
    private javax.swing.JLabel gstInLabel2;
    private javax.swing.JLabel gstInLabel3;
    private javax.swing.JLabel gstInLabel4;
    private javax.swing.JLabel gstInLabel5;
    private javax.swing.JLabel gstInLabel6;
    private javax.swing.JLabel gstInLabel7;
    private javax.swing.JLabel gstInLabel8;
    private javax.swing.JLabel gstInValue2;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JTextField hsnCode;
    private javax.swing.JLabel invoiceSerialLabel3;
    private javax.swing.JLabel invoiceSerialLabel4;
    private javax.swing.JLabel invoiceSerialLabel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel mobileLable;
    private javax.swing.JLabel placeSupplyLabel1;
    private javax.swing.JLabel placeSupplyLabel2;
    private javax.swing.JLabel placeSupplyLabel3;
    private javax.swing.JLabel placeSupplyLabel4;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productRate;
    private javax.swing.JTextField productyQuantity;
    private javax.swing.JLabel receiverNameLabel;
    private javax.swing.JLabel recieverDetailsLabel;
    private javax.swing.JTextField supplyPlaceText1;
    private javax.swing.JTextField supplyPlaceText2;
    private javax.swing.JTextField supplyPlaceText3;
    private javax.swing.JTextField supplyPlaceText4;
    private javax.swing.JTextField supplyPlaceText5;
    private javax.swing.JTextField supplyPlaceText6;
    private javax.swing.JLabel taxChargeLabel2;
    private javax.swing.JComboBox<String> taxComboOption2;
    private javax.swing.JPanel taxDetailsPanel1;
    private javax.swing.JPanel taxDetailsPanel2;
    private javax.swing.JLabel transportModeLabel1;
    private javax.swing.JLabel transportModeLabel2;
    private javax.swing.JTextField transportModeText2;
    private javax.swing.JLabel vehicleNoLabel1;
    private javax.swing.JLabel vehicleNoLabel2;
    private javax.swing.JTextField vehicleNoText1;
    private javax.swing.JTextField vehicleNoText2;
    private javax.swing.JTextField vehicleNoText3;
    private javax.swing.JTextField vehicleNoText4;
    private javax.swing.JTextField vehicleNoText5;
    private javax.swing.JTextField vehicleNoText6;
    private javax.swing.JTextField vehicleNoText7;
    private javax.swing.JTextField vehicleNoText8;
    // End of variables declaration//GEN-END:variables
}
